name: "@vuemicro/auth - build & deployment"

on:
  push:
    branches: [main]
    paths:
      - "packages/auth/**"

jobs:
  deployment:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]

    steps:
      - name: Checkout the repository
        uses: actions/checkout@master

      - name: Setup node with version ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install @vuemicro/auth package dependencies
        run: yarn workspace @vuemicro/auth install

      - name: Runs build for the @vuemicro/auth package
        run: yarn auth:build

      # - uses: ./.github/actions/deploy
      #   env:
      #     DEST_DIR: "@vuemicro-auth"
      #     SOURCE_DIR: "packages/auth/dist"
