name: "@vuemicro/records - build & deployment"

on:
  push:
    branches: [main]
    paths:
      - "packages/records/**"

jobs:
  deployment:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]

    steps:
      - uses: actions/checkout@master

      - uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - uses: ./.github/actions/build
        env:
          PACKAGE_DIR: "packages/records"

      - uses: ./.github/actions/deploy
        env:
          DEST_DIR: "@vuemicro-records"
          SOURCE_DIR: "packages/records/dist"
