name: "@vuemicro/root - build & deployment"

on:
  push:
    branches: [main]
    paths:
      - "packages/root/**"

jobs:
  deployment:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]

    steps:
      - name: Checkout the repository
        uses: actions/checkout@master

      - name: Setup node with version ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install @vuemicro/root package dependencies
        run: yarn workspace @vuemicro/root install

      - name: Runs build for the @vuemicro/root package
        run: yarn root:build

      - name: Runs deploy for the @vuemicro/root package
        uses: jakejarvis/s3-sync-action@master
        with:
          args: --acl public-read --delete
        env:
          DEST_DIR: "@vuemicro-root"
          SOURCE_DIR: packages/root/dist
          AWS_S3_BUCKET: ${{ secrets.S3_BUCKET }}
          AWS_REGION: ${{ secrets.S3_BUCKET_REGION }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
